### ISSUE TITLE
/var/lib/onetime/lib/onetime/email.rb:25:in `block in setup': undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by dober** [dismantl/onetimesecret-docker#3]
Hi

```Setting email sender name to John Doe
/var/lib/onetime/lib/onetime/email.rb:25:in `block in setup': undefined method `[]' for nil:NilClass (NoMethodError)
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/mail-2.5.4/lib/mail/mail.rb:106:in `instance_eval'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/mail-2.5.4/lib/mail/mail.rb:106:in `defaults'
	from /var/lib/onetime/lib/onetime/email.rb:22:in `setup'
	from /var/lib/onetime/lib/onetime.rb:52:in `load!'
	from config.ru:28:in `block in <main>'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
	from config.ru:1:in `new'
	from config.ru:1:in `<main>'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/rack/adapter/loader.rb:33:in `eval'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/rack/adapter/loader.rb:33:in `load'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/controllers/controller.rb:181:in `load_rackup_config'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/controllers/controller.rb:71:in `start'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/runner.rb:187:in `run_command'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/runner.rb:152:in `run!'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/bin/thin:6:in `<top (required)>'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/bin/thin:22:in `load'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/bin/thin:22:in `<main>'
Setting email sender name to John Doe
/var/lib/onetime/lib/onetime/email.rb:25:in `block in setup': undefined method `[]' for nil:NilClass (NoMethodError)
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/mail-2.5.4/lib/mail/mail.rb:106:in `instance_eval'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/mail-2.5.4/lib/mail/mail.rb:106:in `defaults'
	from /var/lib/onetime/lib/onetime/email.rb:22:in `setup'
	from /var/lib/onetime/lib/onetime.rb:52:in `load!'
	from config.ru:28:in `block in <main>'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
	from config.ru:1:in `new'
	from config.ru:1:in `<main>'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/rack/adapter/loader.rb:33:in `eval'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/rack/adapter/loader.rb:33:in `load'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/controllers/controller.rb:181:in `load_rackup_config'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/controllers/controller.rb:71:in `start'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/runner.rb:187:in `run_command'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/runner.rb:152:in `run!'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/bin/thin:6:in `<top (required)>'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/bin/thin:22:in `load'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/bin/thin:22:in `<main>'
Setting email sender name to John Doe
/var/lib/onetime/lib/onetime/email.rb:25:in `block in setup': undefined method `[]' for nil:NilClass (NoMethodError)
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/mail-2.5.4/lib/mail/mail.rb:106:in `instance_eval'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/mail-2.5.4/lib/mail/mail.rb:106:in `defaults'
	from /var/lib/onetime/lib/onetime/email.rb:22:in `setup'
	from /var/lib/onetime/lib/onetime.rb:52:in `load!'
	from config.ru:28:in `block in <main>'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
	from config.ru:1:in `new'
	from config.ru:1:in `<main>'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/rack/adapter/loader.rb:33:in `eval'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/rack/adapter/loader.rb:33:in `load'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/controllers/controller.rb:181:in `load_rackup_config'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/controllers/controller.rb:71:in `start'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/runner.rb:187:in `run_command'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/runner.rb:152:in `run!'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/bin/thin:6:in `<top (required)>'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/bin/thin:22:in `load'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/bin/thin:22:in `<main>'
Setting email sender name to John Doe
/var/lib/onetime/lib/onetime/email.rb:25:in `block in setup': undefined method `[]' for nil:NilClass (NoMethodError)
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/mail-2.5.4/lib/mail/mail.rb:106:in `instance_eval'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/mail-2.5.4/lib/mail/mail.rb:106:in `defaults'
	from /var/lib/onetime/lib/onetime/email.rb:22:in `setup'
	from /var/lib/onetime/lib/onetime.rb:52:in `load!'
	from config.ru:28:in `block in <main>'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
	from config.ru:1:in `new'
	from config.ru:1:in `<main>'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/rack/adapter/loader.rb:33:in `eval'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/rack/adapter/loader.rb:33:in `load'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/controllers/controller.rb:181:in `load_rackup_config'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/controllers/controller.rb:71:in `start'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/runner.rb:187:in `run_command'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/runner.rb:152:in `run!'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/bin/thin:6:in `<top (required)>'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/bin/thin:22:in `load'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/bin/thin:22:in `<main>'
Setting email sender name to John Doe
/var/lib/onetime/lib/onetime/email.rb:25:in `block in setup': undefined method `[]' for nil:NilClass (NoMethodError)
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/mail-2.5.4/lib/mail/mail.rb:106:in `instance_eval'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/mail-2.5.4/lib/mail/mail.rb:106:in `defaults'
	from /var/lib/onetime/lib/onetime/email.rb:22:in `setup'
	from /var/lib/onetime/lib/onetime.rb:52:in `load!'
	from config.ru:28:in `block in <main>'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
	from config.ru:1:in `new'
	from config.ru:1:in `<main>'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/rack/adapter/loader.rb:33:in `eval'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/rack/adapter/loader.rb:33:in `load'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/controllers/controller.rb:181:in `load_rackup_config'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/controllers/controller.rb:71:in `start'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/runner.rb:187:in `run_command'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/runner.rb:152:in `run!'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/bin/thin:6:in `<top (required)>'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/bin/thin:22:in `load'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/bin/thin:22:in `<main>'
Setting email sender name to John Doe
/var/lib/onetime/lib/onetime/email.rb:25:in `block in setup': undefined method `[]' for nil:NilClass (NoMethodError)
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/mail-2.5.4/lib/mail/mail.rb:106:in `instance_eval'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/mail-2.5.4/lib/mail/mail.rb:106:in `defaults'
	from /var/lib/onetime/lib/onetime/email.rb:22:in `setup'
	from /var/lib/onetime/lib/onetime.rb:52:in `load!'
	from config.ru:28:in `block in <main>'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
	from config.ru:1:in `new'
	from config.ru:1:in `<main>'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/rack/adapter/loader.rb:33:in `eval'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/rack/adapter/loader.rb:33:in `load'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/controllers/controller.rb:181:in `load_rackup_config'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/controllers/controller.rb:71:in `start'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/runner.rb:187:in `run_command'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/lib/thin/runner.rb:152:in `run!'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/gems/thin-1.5.0/bin/thin:6:in `<top (required)>'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/bin/thin:22:in `load'
	from /var/lib/onetime/vendor/bundle/ruby/2.3.0/bin/thin:22:in `<main>```

**Comment by dismantl** [comment]
I'm gonna need some more details about what you're trying to do in order to help you with this error.

**Comment by dober** [comment]
Oh, sorry
Im trying to run docker-compose.yml from your repo and config files:
- config
- redis.conf

**Comment by dober** [comment]
@dismantl is the issue reproducible?

**Comment by dismantl** [comment]
I have not been able to reproduce this. The latest updates to the repo including newer versions of Ruby and OTS which would hopefully mitigate errors like this. Closing for now.
